---
include:
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.103/terraform-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.103/git-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.103/gitlab-toolkit.yml"
  - remote: "https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.103/docker-toolkit.yml"



get-latest-terraform:
  extends: .get-latest-terraform

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate-terraform
  variables:
    ENVIRONMENTS: examples/complete

terratest:
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  image: golang
  before_script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - curl https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o terraform_1.7.5_linux_amd64.zip
    - apt update
    - apt install zip -y
    - unzip awscliv2.zip
    - unzip terraform_1.7.5_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - ./aws/install
    - !reference [ .oidc-login, script ]

  script:
    - cd tests
    - go mod tidy
    - go test my_test.go
  tags:
    - miquido
    - docker

bump-tag:
  extends: .bump_minor_tag

docs:
  extends: .generate_readme
  stage: .post

push_readme:
  extends: .push_readme
  stage: .post
  dependencies: [ "docs" ]
  needs: [ "docs" ]
